### ISSUE TITLE
Autowiring requires classmap configuration

### ISSUE THREAD

**Issue by arueckauer** [opsway/laminas-service-manager-attributes#2]
Unless I am missing something, this component requires Composer classmap configuration regardless of a PSR-4 namespacing.

The [arueckauer/di-autowire](https://github.com/arueckauer/di-autowire) repository demonstrates this. The main branch is not working, but [fix/add-classmap-to-fix-autowire](https://github.com/arueckauer/di-autowire/tree/fix/add-classmap-to-fix-autowire) is.

Is it possible to get this working without a classmap?

**Comment by mrVrAlex** [comment]
You should use composer config (https://github.com/arueckauer/di-autowire/blob/main/composer.json#L18) with added
`"optimize-autoloader": true,` option 
OR use `composer install -o` "-o" param when install/upgrade packages.

**Comment by arueckauer** [comment]
Gotcha. So, in a development scenario that means running `composer dump-autoload` is required each time a new service is declared?

**Comment by mrVrAlex** [comment]
Yes, of course. All new added files should be generated in composer classmap list first, then attribute builder can scan, read & make updated config for service manager.
